# Generated by Django 5.0.6 on 2025-11-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FurnaceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Simulation Run', max_length=100)),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('fuel_hhv_mj_kg', models.FloatField(default=16.0, verbose_name='Fuel HHV (MJ/kg)')),
                ('moisture_percent', models.FloatField(default=10.0, verbose_name='Moisture (%)')),
                ('excess_air_percent', models.FloatField(default=30.0, verbose_name='Excess Air (%)')),
                ('calculated_efficiency', models.FloatField(blank=True, null=True, verbose_name='Efficiency (%)')),
                ('exhaust_temp_c', models.FloatField(blank=True, null=True, verbose_name='Exhaust Temp (°C)')),
                ('flue_gas_co2_percent', models.FloatField(blank=True, null=True, verbose_name='Flue Gas CO2 (%)')),
                ('plot_base64', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
