# Generated by Django 5.0.6 on 2025-11-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustion_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnacerun',
            name='t_adiabatic_c',
            field=models.FloatField(blank=True, null=True, verbose_name='Adiabatic Temp (°C)'),
        ),
    ]
