# Generated by Django 5.0.6 on 2025-11-03 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustion_app', '0002_furnacerun_t_adiabatic_c'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('C', models.FloatField(default=0.35, verbose_name='Carbon (C) %')),
                ('H', models.FloatField(default=0.04, verbose_name='Hydrogen (H) %')),
                ('O', models.FloatField(default=0.4, verbose_name='Oxygen (O) %')),
                ('N', models.FloatField(default=0.005, verbose_name='Nitrogen (N) %')),
                ('S', models.FloatField(default=0.005, verbose_name='Sulfur (S) %')),
                ('Ash', models.FloatField(default=0.2, verbose_name='Ash %')),
                ('hhv_mj_kg', models.FloatField(default=16.0, verbose_name='HHV (MJ/kg)')),
            ],
        ),
        migrations.RemoveField(
            model_name='furnacerun',
            name='fuel_hhv_mj_kg',
        ),
        migrations.RemoveField(
            model_name='furnacerun',
            name='plot_base64',
        ),
        migrations.AddField(
            model_name='furnacerun',
            name='fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='combustion_app.fuel'),
        ),
    ]
