# Generated by Django 5.0.6 on 2025-11-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustion_app', '0004_initial_fuels'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='cost_per_tonne',
            field=models.FloatField(default=50.0, verbose_name='Cost ($/tonne)'),
        ),
        migrations.AddField(
            model_name='furnacerun',
            name='cost_per_gj',
            field=models.FloatField(blank=True, null=True, verbose_name='Cost ($/GJ)'),
        ),
        migrations.AddField(
            model_name='furnacerun',
            name='cost_per_hour',
            field=models.FloatField(blank=True, null=True, verbose_name='Cost ($/hr)'),
        ),
        migrations.AddField(
            model_name='furnacerun',
            name='emissions_co_ppm',
            field=models.FloatField(blank=True, null=True, verbose_name='CO (ppm)'),
        ),
        migrations.AddField(
            model_name='furnacerun',
            name='emissions_nox_ppm',
            field=models.FloatField(blank=True, null=True, verbose_name='NOx (ppm)'),
        ),
        migrations.AddField(
            model_name='furnacerun',
            name='furnace_load_gj_hour',
            field=models.FloatField(default=1.0, verbose_name='Furnace Load (GJ/hr)'),
        ),
    ]
