# Generated by Django 5.0.6 on 2025-11-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustion_app', '0005_fuel_cost_per_tonne_furnacerun_cost_per_gj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='cost_per_tonne',
            field=models.FloatField(default=50.0, verbose_name='Cost (₹/tonne)'),
        ),
        migrations.AlterField(
            model_name='furnacerun',
            name='cost_per_gj',
            field=models.FloatField(blank=True, null=True, verbose_name='Cost (₹/GJ)'),
        ),
        migrations.AlterField(
            model_name='furnacerun',
            name='cost_per_hour',
            field=models.FloatField(blank=True, null=True, verbose_name='Cost (₹/hr)'),
        ),
    ]
